[package]
name = "farid"
version = "0.1.1"
edition = "2021"
authors = ["Zahash <zahash.z@gmail.com>"]
description = "Extensible Unique Id Generation for Rust."
license = "MIT"
repository = "https://github.com/zahash/farid"

[dependencies]
